### ISSUE TITLE
Priority Class is missing when deploying shoot

### ISSUE THREAD

**Issue by tuxgoose** [gardener/gardener-extension-networking-calico#199]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
FailedCreate  3m50s (x22 over 75m)  replicaset-controller  Error creating: pods "calico-typha-horizontal-autoscaler-78c69b844-" is forbidden: no PriorityClass with name gardener-shoot-system-800 was found

**What you expected to happen**:
Replica sets to be deployed an running inside of calico extension 
**How to reproduce it (as minimally and precisely as possible)**:
deploy a shoot with this extension and it is missing the prority class

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
I assume this issue can be caused by https://github.com/gardener/gardener-extension-networking-calico/pull/192. However the corresponding PR has a release note of type `breaking` that the corresponding version of netwotking-calico (v1.25.0) requires at least Gardener v1.50. I assume the Gardener version in your setup was a lower one.

Feel free to reopen if you can reproduce with Gardener v1.50+.
/close
